### ISSUE TITLE
Fix mobile

### ISSUE THREAD

**Issue by aikenahac** [MaticBabnik/easistent-tt#2]
Fix mobile view plz

![Screenshot_20220209-234225_Firefox.png](https://user-images.githubusercontent.com/30961404/153302928-d9286883-f151-444f-a1e9-c4283ebc1237.png)

![Screenshot_20220209-234228_Firefox.png](https://user-images.githubusercontent.com/30961404/153302951-4fc9576c-05aa-47f8-9f9a-7ad45c57dd18.png)

**Comment by MaticBabnik** [comment]
https://github.com/MaticBabnik/timetable-vue
