### ISSUE TITLE
Urniki se ne strinjajo med seboj

### ISSUE THREAD

**Issue by ghost** [MaticBabnik/easistent-tt#6]
![unknown-1](https://user-images.githubusercontent.com/36968169/196371875-833e9ff5-b1ec-4ca4-8509-7efa597f44e2.png)
![unknown](https://user-images.githubusercontent.com/36968169/196371882-8044ca77-0270-4309-8e67-4defd9755f27.png)
(seveda je problem v bližini MK)

**Comment by MaticBabnik** [comment]
Te gimnazijski urniki so cist cursed...

bom pogledu do petka. (surely...)

**Comment by sijanec** [comment]
![bdd0kylwwsk81](https://user-images.githubusercontent.com/42650898/196500067-8e60d58a-88d0-4379-ad0a-b7d3f6847ff8.jpg)
i feel u hehehe, faaking gimnazijski informacijski sistemi

**Comment by aikenahac** [comment]
Skill issue od ljudi k dela gim urnik.
sorry no fix, cope

**Comment by ghost** [comment]
> Skill issue od ljudi k dela gim urnik. sorry no fix, cope

Kaj misliš da do sedaj delamo?
Lp lokalni gim. Coper

**Comment by ghost** [comment]
Relevantnost problema minila v mojih očeh

**Comment by MaticBabnik** [comment]
lol

**Comment by ghost** [comment]
če se ne strinjate lahko še enkrat odprem problem
